l_spanish:
 # mod
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "Aggiornamento"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "Conferma"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "Mai"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_TITLE: "Campo titolo sotto,"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_EDIT_DESC: "Campo descrizione sotto,"

 # vanilla
 MESSAGE_SETTINGS_WINDOW_NAME: "Impostazioni messaggi"
 MESSAGE_SETTINGS_WINDOW_SHORTCUT_TT: "#I Fai clic per aprire Impostazioni messaggi#!"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nModifica la frequenza e la visibilità dei messaggi per gruppi filtrati."
 MESSAGE_SETTINGS_WINDOW_RESET: "Ripristina predefiniti"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Ripristina impostazioni messaggi#!\n#I Fai clic per ripristinare le modifiche correnti alle impostazioni predefinite#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Applica modifiche"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Fai clic per chiudere la finestra Impostazioni messaggi e salvare le modifiche correnti#!"
 MESSAGE_SETTINGS_WINDOW_GROUP_HEADER: "$NAME$ #weak ($SIZE$)#!"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Gruppo filtro"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Nome del gruppo di filtro dei messaggi"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Aspetto"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Come visualizzare i messaggi di questo gruppo filtro"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pausa"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Se il gioco dovrebbe mettere in pausa quando appaiono messaggi di questo filtro"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Attiva/disattiva pausa automatica#!\n#I Attiva/disattiva per mettere in pausa il gioco quando appaiono messaggi di questo filtro#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Ignora messaggio#!\n#I Fai clic per ignorare il messaggio corrente e mostrare il messaggio successivo nella coda#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TITLE: "Messaggio personalizzato"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_TT: "#T Messaggio personalizzato#!\n#I Fai clic per scrivere un messaggio personalizzato a te stesso e selezionare quando desideri riceverlo#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DATE: "Data di arrivo: [DATE.GetString|V]"

 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD: "Scarta"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DISCARD_TT: "#T Scarta messaggio#!\n#I Fai clic per scartare il messaggio corrente#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND: "Invia"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_SEND_TT: "#T Invia#!\n#I Fai clic per inviare il messaggio corrente#!"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_DAY: "Giorno"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_MONTH: "Mese"
 MESSAGE_SETTINGS_WINDOW_CUSTOM_MESSAGE_YEAR: "Anno"
